#ifndef DELAUNAY_H
#define DELAUNAY_H

#include <iostream>
#include <stdlib.h>
#include <cmath>

#include "vector.h"

/*!\brief Generates a triangulation of the polygon mesh that gets passed in
 * -- I may not actually implement this one and leave it in the window, that we
 *  we can see it build the geometry.
 */
void Triangulate();

/*!\brief Used by c qsort method to sort the vertices
 */
int VertextCompare(const void *v1, const void *v2);

/*!\brief Used to determine if test_point lies within circle generated by
 * p1, p2, and p3
 *
 * The center of the circle is placed in ret_pt.
 * A point on the edge is inside the circle
 */
bool CircleIntersect(Vector2<float> test_point,
		Vector2<float> p1, Vector2<float> p2, Vector2<float> p3,
		Vector2<float>& ret_pt);

#endif //DELAUNAY_H
