#ifndef DELAUNAY_H
#define DELAUNAY_H

#include <iostream>
#include <stdlib.h>
#include <cmath>

#include "vector.h"

#define DEL_EPS	0.000001

/*!\brief Used to determine if test_point lies within circle generated by
 * p1, p2, and p3
 *
 * The center of the circle is placed in ret_pt.
 * A point on the edge is inside the circle
 */
static bool CircleIntersect(Vector2<float> test_point,
		Vector2<float> p1, Vector2<float> p2, Vector2<float> p3,
		Vector2<float>& ret_pt);

#endif //DELAUNAY_H
